package com.agenda.model;
// Generated 23/03/2015 08:38:43 PM by Hibernate Tools 4.3.1

import java.util.Iterator;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name="proyecto"
    ,catalog="agenda"
)
public class Proyecto  implements java.io.Serializable {


     private Integer proyectoId;
     private String nombre;
     private String descripcion;
     private Set<Tarea> Tareas;

    public Proyecto() {
    }

    public Proyecto(String nombre, String descripcion) {
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
     @OneToMany(mappedBy="proyecto", cascade = CascadeType.ALL)

    
    @Column(name="proyecto_id", unique=true, nullable=false)
    public Integer getProyectoId() {
        return this.proyectoId;
    }
    
    public void setProyectoId(Integer proyectoId) {
        this.proyectoId = proyectoId;
    }

    
    @Column(name="nombre", nullable=false, length=60)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(mappedBy="Proyecto",cascade= CascadeType.ALL)
    public Set<Tarea> getTareas() {
        return Tareas;
    }

    public void setTareas(Set<Tarea> Tareas) {
        this.Tareas = Tareas;
    }

    public Iterator iterator() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


